version: '3.8'

services:
  prod:
    container_name: Marketplace_backend_prod
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3003:3003
      - $PORT:$PORT
      - $WEB_SOCKET_PORT:$WEB_SOCKET_PORT
    depends_on:
      - mysqldb
    env_file: ./.env
    environment:
      SITE_URL: $SITE_URL
      IMAGE_SITE_URL: $IMAGE_SITE_URL
      PORT: $PORT
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      DB_NAME: $DB_NAME
      DB_PORT: $DB_PORT
      JWT_SECRET: $JWT_SECRET
      JWT_EXPIRY: $JWT_EXPIRY
      GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
      GOOGLE_SECRET: $GOOGLE_SECRET
      FB_APP_ID: $FB_APP_ID
      FB_APP_SECRET: $FB_APP_SECRET
      SENDGRID_HOST: $SENDGRID_HOST
      SENDGRID_PORT: $SENDGRID_PORT
      SENDGRID_USER_EMAIL: $SENDGRID_USER_EMAIL
      SENDGRID_USER: $SENDGRID_USER
      SENDGRID_API: $SENDGRID_API
      SENTRY_DNS: $SENTRY_DNS
      STRIPE_RETURN_URL: $STRIPE_RETURN_URL
      STRIPE_REFRESH_URL: $STRIPE_REFRESH_URL
      STRIPE_SECRET_KEY: $STRIPE_SECRET_KEY
      STRIPE_PUBLISHER_KEY: $STRIPE_PUBLISHER_KEY
      STRIPE_ACCOUNT_ID: $STRIPE_ACCOUNT_ID
      CRIIPTO_ISSUER: $CRIIPTO_ISSUER
      CRIIPTO_TOKEN_URL: $CRIIPTO_TOKEN_URL
      CRIIPTO_USERINFO_URL: $CRIIPTO_USERINFO_URL
      CRIIPTO_AUTHORIZATION_URL: $CRIIPTO_AUTHORIZATION_URL
      CRIIPTO_CLIENT_ID: $CRIIPTO_CLIENT_ID
      CRIIPTO_CLIENT_SECRET: $CRIIPTO_CLIENT_SECRET
      CRIIPTO_ACR_VALUES: $CRIIPTO_ACR_VALUES
      WEB_SOCKET_PORT: $WEB_SOCKET_PORT
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  mysqldb:
    container_name: marketplace_database
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_HOST: $DB_HOST
      MYSQL_ROOT_PASSWORD: $DB_PASS
      MYSQL_DATABASE: $DB_NAME
      MYSQL_TCP_PORT: $DB_PORT
    ports:
      - $MYSQL_LOCAL_PORT:$DB_PORT
    volumes:
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

  phpmyadmin:
    container_name: marketplace_phpmyadmin
    image: phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
    ports:
      - '$PHP_MY_ADMIN_PORT:80'

volumes:
  mysql:
  mysql_config:
